### ISSUE TITLE
[Task]-HelloWorld1

### ISSUE THREAD

**Issue by annamarieweber** [annamarieweber/Hello-Code#5]
## Task Description
Write lesson for creating a simple hello world program using python

## Task Requirements
- [ ] hello-world.md has instructions for writing a hello world script and running tests to see if it worked
- [ ] hello-world.py file where the hello-world program can be written
- [ ] hello-world_test.py file for testing that the hello world program runs properly

## Task Priority
3
